- cypress/plugins/index.js
- src/pages/_document.js
- src/pages/index.js
The problem was that material ui uses jss for styling so the styles were being loaded post javascript loaded. We just needed to add a custom document and inject the styles there so they can be rendered server side.
> fix: #158 flash glitch

- src/components/VerifiedBadge.cy.js
- src/components/VerifiedBadge.js
Added Badge component. The reason the photo is the wrong color is because The ThemeProvider isn't mounted by Cypress, Some of the other component tests that were dependent on the theme had the same issues so we probably need to raise this as an issue. If you put the component in the applciaion it will be green when enabled and low opacity white/grey when disabled.
> feat: badge component #154

- cypress/support/components-testing.js
- package-lock.json
- package.json
resolves #230 
I resolved this by adding webfontloader as a dev package and using the cypress support file to run it before each test.
I also added `"cyux": "rm -rf .next/; npm run cyu",` as a helper script until #229 is resolved
> fix: cypress-ct font loading

- README.md
I noticed a mistake in my instructions and also added wsl 1 instructions.
> fix: readme wsl instructions for cypress

- src/components/App.js
Fix the bug, by testing if the  MapContext has already updated the map object.
I think it's can be fixed in a better way, by moving the creation of the Map object inside MapContextProvider, and providing for the consumer's context just a init function instead of setMap, but NextJS don't allow the import of the class Map.
> fix: auto-refreshing the page in dev mode #255

- src/models/utils.js
- src/models/utils.test.js
- To test this function, the use of fetch in jest/nodeJS environment will not work. fetch don't exist. instead, if we use Axios, it's throw an error when the server returns a 4XX/5XX response ( for the 404 bugs).
- for the test a just test it with a wrong URL, tell me if they are other URLs to test I will make changes for that.
> fix: add test to requestAPI, and modify requestAPI to use axios … #275

- src/components/App.js
depends on https://github.com/Greenstand/treetracker-web-map-core/pull/27
This fixes the import to go along with changes to the web-map-core repo
> Hotfix: Map import

- .husky/pre-commit
- .lintstagedrc.js
This configuration will avoid linting changed files that have not been staged. Suppose you have changed several files and want to stage and commit only one file. The current configuration will lint all changed files. This new config will only lint the staged file(s). If `.eslintrc` or `eslintignore` has been changed then the entire project will be linted to prevent rule changes from introducing new errors.
> fix: lint-staged settings

- src/components/Link.js
This is some sort of issue with the custom `Link` component with the new setup. I tried copying the [latest example from mui-org](https://github.com/mui-org/material-ui/blob/master/examples/nextjs/src/Link.js) but it did not make a difference. 
Fixes #316
> fix: remove underscore style from Link component

- src/pages/_document.js
I was able to locate the font error and fix #291  - Montserrat font weight 600 was not being imported, so font weight 700 was being used by default, causing the disparity in font weight compared to the figma docs.
Visual confirmation (this PR is a simple four-character change to a font import so that 600 weight Montserrat is actually available in the application.)
> fix: google font imports

- src/components/InformationCard1.cy.js
- src/components/InformationCard1.js
Signed-off-by: Jay Clark <jay@jayeclark.dev>
Updates InformationCard CSS to more closely match figma docs, and converts hardcoded values for font color and padding/margin to theme values where possible.
Fixes #300
> fix: update informationCard CSS to match figma

- README.md
- cypress.json
- cypress/plugins/index.js
- cypress/tests/integration/organizations/[organizationid].cy.js
- cypress/tests/integration/top.cy.js
- cypress/tests/integration/trees/[treeid].cy.js
- package.json
This adds the option to open cypress without starting a nextjs server to use nock. `npm run cy` will now start cypress without nock. This means you will need to start the web server separately with `npm run dev` or `npm start`. To run cypress with nock (old behavior) use the new script `npm run cy:nock`. This sets a [cypress environment variable ](https://docs.cypress.io/guides/guides/environment-variables#Option-4-env) which can be used to check if the nock server is active. Previous uses of nock have been updated to skip if environment variable is not set. 
Fixes #337 
> feat: cypress open without nock

- README.md
- src/DesignSandbox.cy.js
- src/DesignSandbox.js
- src/components/BackButton.js
- src/components/Home.js
- src/components/InformationCard1.js
- src/components/Navbar.js
- src/components/SearchButton.js
- src/components/TreeSpeciesCard.js
- src/components/VerifiedBadge.js
- src/components/common/CustomCard.js
- src/pages/planters/[planterid].js
- src/pages/trees/[treeid].js
- src/theme.js
Suggestions and ideas are welcome with the naming of the colors or anything that seems can be arranged into a more logical order. Not sure about file placement. But that's what I came up with which organizes the colors and the typography of the project.
Adjusted the colors and typography in the project according to this style sheet. 
Parts that I did not change: 
TreeAge component: I will fix this in #302
Organization Page: I will raise a separate issue for this, as this page is really behind the others.
Time and Location component: These two components are basically the same. I think they should be merged into one component. If that's ok I will raise an issue for this as well, (I'm halfway done with this.)
Fixes #301 
> style: add sandbox for colors and typography

- src/components/FeaturedTreesSlider/style.js
Adapt FeaturedTreesSlider to mobile device
Fixes #346
(already existed: https://github.com/Greenstand/treetracker-web-map-client/blob/web-map-site/src/components/FeaturedTreesSlider/test.cy.js)
> feat: adapt FeaturedTreesSlider to mobile device (issue #346)

- package-lock.json
here's a fix for the new security warning that shows up with `npm audit --production`.
```
next  <11.1.3
Severity: high
Unexpected server crash in Next.js - https://github.com/advisories/GHSA-25mp-g6fv-mqxx
fix available via `npm audit fix`
node_modules/next
```
> fix: security audit

- .github/ISSUE_TEMPLATE/basic-issue.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/component-building.md
- doc/web-map-api.yaml
- src/DesignSandbox.cy.js
- src/DesignSandbox.js
- src/components/Home.js
- src/components/InformationCard1.js
- src/components/PageWrapper.js
- src/components/TreeSpeciesCard.js
- src/components/VerifiedBadge.js
- src/components/common/CustomCard.js
- src/components/common/Filter.js
- src/components/common/TreeTag.js
- src/pages/planters/[planterid].js
- src/pages/top.js
- src/pages/trees/[treeid].js
- src/theme.js
Font sizes are responsive on their own now (check the design first though, you might find some differences from the main style from time to time).
Padding and margins are not, they have to be done manually. Did this on the planter and tree page.
Fixes #344
> Issue #344 mobile design

- src/components/common/CustomCard.js
- src/pages/organizations/[organizationid].js
- src/pages/planters/[planterid].js
Aligned the custom cards properly to be centered and the same width on all screens. Fixed it on the planter page, there was also some misalignment.
Sidenote: "Associated Organizations" is a long title for the card. So I shortened it to "Ass. orgs.". It feels a bit of a "hacky" solution, but the long word will mess up the style of the card one way or another. So I'm fine with it.
Fixes #409
> style: issue #409 css problem align custom cards

- src/components/InformationCard1.js
Add default bg image for informationCard component.
Fixes #417
___
There is another solution I came up with:
Personally prefer the first one, fits better with the design IMO. That's the solution I went with in this PR. Let me know what you think.
> feat: issue #417 default bg image

- src/components/App.js
- Added iconSuite to map options and set it to 'green'
- Removed tileServerUrl and tileServerSubdomain because it will be set by map-core based on iconSuite setting
> style: switch to green icon suite

- package-lock.json
I noticed a new security warning in the main dependencies, an automatic fix was available.
```
follow-redirects  <1.14.7
Severity: high
Exposure of sensitive information in follow-redirects - https://github.com/advisories/GHSA-74fj-2j2h-c42q
fix available via `npm audit fix`
node_modules/follow-redirects
```
> hotfix: 'follow-redirects' security warning

- src/components/BackButton.js
- src/components/InformationCard1.js
- src/components/VerifiedBadge.js
- src/components/common/CustomImageWrapper.js
- src/components/common/TreeTag.js
- src/pages/trees/[treeid].js
- src/theme.js
Refined the trees page styling to get as close to the Figma design as possible. 
In some places, there are font weights 500 and 800 which are not valid for Lato. I used 400 and 700 instead.
Fixes #442
> style: issue #442 refine trees page

- package-lock.json
automatic fixes for the following security alerts:
```
nanoid  <3.1.31
Severity: moderate
Exposure of Sensitive Information to an Unauthorized Actor in nanoid - https://github.com/advisories/GHSA-qrpm-p2h7-hrv2
fix available via `npm audit fix`
node_modules/nanoid
next  9.0.6-canary.0 - 9.3.4-canary.0 || 10.0.2-canary.0 - 11.1.3 || 12.0.0 - 12.0.9-canary.12
Severity: high
DOS Vulnerability in next.js - https://github.com/advisories/GHSA-wr66-vrwm-5g5x
Depends on vulnerable versions of node-fetch
fix available via `npm audit fix`
node_modules/next
node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix` …
```
> fix: security warnings

- src/components/App.js
**Enable Map zoom controls**
<s>The google maps default zoom control location is on the top left.  I attempted to set the position to bottom right, but there is a race condition between the async google maps script loading and the greenstand map initialization.  Without some involved handling of those two events it's tough to set the zoomControlOptions.  Maybe that could be a follow up to this PR if someone can figure it out.  I realize this does not meet the requirement of zoom buttons on the **bottom right**. </s>
Fixes #332
https://github.com/Greenstand/treetracker-web-map-core/pull/86
This and its dependent PR can be merged/released in any order without …
> feat: zoom controls

- src/components/common/CustomImageWrapper.js
[comment]: #445 keep the FB button permanently on the photo now'
Fixes #445 The like button animation is slow
[comment]: 
- Bug fix (non-breaking change which fixes an issue)
- Cypress integration
> Show FB button permanently

- package-lock.json
- package.json
Nextjs was updated to a canary release for #470. A new release version came out yesterday so we should update to avoid any possible issues in the unstable version. 
https://github.com/vercel/next.js/releases/tag/v12.1.0
> build: update nextjs to stable version

- src/components/CustomWorldMap.cy.js
- src/components/CustomWorldMap.js
- src/pages/organizations/[organizationid].js
- src/pages/planters/[planterid].js
The world map component is not clickable. It always shows the tooltip. For positioning the tooltip created two objects that contain the positions for each continent, one for mobile and one for desktop screens.
Right now it just shows Africa as the default, should be updated once we can get the continent name.
As a prop ('con') it accepts not the continent name but a shortened continent code `['na', 'sa', 'af', 'eu', 'as', 'oc']`.
Fixes #421
> fix: issue #421 world map should not be clickable

- src/context/themeContext.js
- src/hooks/useLocalStorage.js
Usage: Similar to useState. Accepts a key, value pair. For example:
```
const [mode, setMode] = useLocalStorage('theme', 'light');
```
Fixes #475
> feat: issue #475 add localstorage hook

- src/style.css
Moved copyright panel behind drawer.
Fixes #495
> fix: issue #495 move copyright panel behind drawer

- src/models/utils.js
Fixes #532 
The fixCountryNames function in models/utils to get the correct Alpha2 code was changed. It shouldn't be necessary to have this function because the correct Alpha2 codes are fetched anyways, but kept both countries in that function to avoid any more issues.
> fix: missing flags for 2 countries added back

- src/components/common/CustomShareIcon.js
[comment]: # added an onClick={handleOnClick} to CustonShareIcon.js, when handleOnClick was being used in Share.js it wasnt doing anything as it wasnt being told what to do
Fixes #562 
> fix(sharebutton): added onClick to CustomShareIcon

- src/pages/trees/[treeid].js
[comment]: # 
Fixes #579 
- [x ] Bug fix (non-breaking change which fixes an issue)
no cypress file for [treeid].js
- [ x] I have commented my code, particularly in hard-to-understand areas
> fix: shortened gps location numbers

- src/components/App.js
Fixes the error thrown by the repeated forward slash in href when switching between trees.
Bug occurs when switching between the trees
:-:
> fix: repeated forward slash in href

- src/components/InformationCard1.js
When passing style props directly to a MUI component React gives an annoying warning. These props should be passed through the `sx` prop.
```js
Warning: React does not recognize the `flexDirection` prop on a DOM element.
If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `flexdirection` instead.
If you accidentally passed it from a parent component, remove it from the DOM element.
```
> fix: react prop warning

- src/components/LayoutEmbed.js
- src/style.css
Fixes Tiny CSS Issue #552
Before:
After:
> fix: tiny css problem #552

- src/components/playground/ColorInput.cy.js
- src/components/playground/ColorInput.js
- src/components/playground/ColorThumbnail.cy.js
- src/components/playground/ColorThumbnail.js
- src/components/playground/SelectColorProp.cy.js
- src/components/playground/SelectColorProp.js
- src/components/playground/SelectTypographyProp.cy.js
- src/components/playground/SelectTypographyProp.js
- src/components/playground/TypographyInput.cy.js
- src/components/playground/TypographyInput.js
- src/components/playground/TypographyThumbnail.cy.js
- src/components/playground/TypographyThumbnail.js
- src/models/themePlaygroundOptions.js
- src/pages/admin/theme.js
Support rendering from the customizeOptions object.
Reduce 'prop drilling' by getting theme data in the lowest Components. 
Fixes #671
> refactor: improve render theme customization

- next.config.js
Uses 308 redirect instead of 301, but these are basically same thing. If anything, 308 is slightly better. Only did this as its out of the box with next.js https://nextjs.org/docs/api-reference/next.config.js/redirects
redirects allow and URL the has the query treeid or userid to redirect, e.g. /foo/bar?treeid=123 redirects to /trees/123?treeid=123 (will not redirect if path contains 'trees' or 'planters' to prevent infinite redirect loop)
next.js also preserves url path by default, kind of annoying but wont hurt anything i cant image. 
also cleaned up other path var names in rewrites, only to keep things consistent. opted for camelCase
Fixes #740
> Legacy query redirects

- src/pages/admin/theme.js
Toggle for preview on Mobile and Desktop
Fixes #668
Mobile Preview (Desktop did not change)
> feat(playground): can preview on mobile/desktop

- src/components/ImpactSection.js
Fixes icon color in dark mode
Before|After
:-:|:-:
> fix: icon no dark mode support

- src/components/Drawer.js
Fixes drawer expand icon color contrast
Before|After
:-:|:-:|
> fix: drawer expand icon color

- src/pages/top.js
Fixes error that occurs on fetching the leaderboard when the continent state changes
> fix: leaderboard fetch on continent

- src/components/LikeButton.js
- src/components/common/CustomImageWrapper.js
- src/pages/trees/[treeid].js
Replace treeId prop with full url prop
Small change to the LikeButton component prop.
Fixes #824
> refactor: re-usable LikeButton

- src/components/ImpactSection.js
Changed the icon colors to be disabled
Fixes #828 
> fix: impact section icon colors

- src/components/ImpactSection.js
Changed the height of the icons to be responsive
Fixes #785
Desktop
|Before
|:-:
|![localhost_3000_trees_186735_embed=false (1)](https://user-images.githubusercontent.com/31519867/185622383-dabee6f6-3c95-4d4c-b6d6-fb29080e282a.png)
|After
|![localhost_3000_trees_186735_embed=false](https://user-images.githubusercontent.com/31519867/185621507-69e33cb1-e96a-4bdc-86fe-cd8968c09367.png)
Mobile
Before|After
:-:|:-:
> fix: impact section icon heights

- src/components/LayoutEmbed.js
Fixed the logo
Add link to Greenstand website as in current version
Fixes #811 
> fix: embed incorrect logo

- src/components/FeaturedPlantersSlider/index.js
- src/pages/top.js
Using ISR for /top, pre-renders /top at build time
Also hot fix for undefined planter image call
for ISR:
- does not run at development build time, only production
- in development, /top is rebuilt on each request
- in production, /top is rebuilt on next call after successful re-render, no more than every 60 seconds (time is flexible obviously)
Fixes #797
> ISR/Cache for /top

- doc/examples/planters/940.json
- src/mocks/handlers.js
- src/pages/top.js
Related to my previous PR for using ISR on the /top page
Basically issue was in dev env, we are using MSW. MSW handlers were designed incorrectly resulting in them returning a single planter/org object when requesting /planters/featured or /organizations/featured (was picking up featured as the ID). However, prod api returns object with an array of planters/orgs inside of it.
In my last PR, I was relying on MSW data to make change that returned [data] instead of data.planters or data.organizations (since mock data returned an object and we were expecting an array).
To fix this, I updated MSW to return data matching that of the prod api and updated the /top ISR usage so we can take advantage of caching. This also involved updating the image key name for the planters.
Fixes #857
[comment]: …
> fix: isr usage of msw

- src/components/LeaderBoard.js
Fixes warning caused by passing an invalid value to `sx` prop
> fix: react sx prop warning

- src/components/Timeline.js
Fixes dark theme text color incorrect
Before|After
:-:|:-:
> fix: timeline dark theme color incorrect

- .github/workflows/pull-request-ci.yml
- cypress/tests/integration/index.cy.js
- feat: updates actions/checkout@v2 to actions/checkout@v3, actions/upload-artifact@v2 to actions/upload-artifact@v3 and cypress-io/github-action@v2 to cypress-io/github-action@v4
- fix: increases home component unit test timeout because it sometimes fail due to longer load time of home page
> workflow updates and cypress home component unit test timeout

- src/pages/organizations/[organizationid].js
- src/pages/planters/[planterid].js
- src/pages/wallets/[walletid].js
Fixes icon color not working in dark mode
Change the green to Greenstand primary color
|Dark|
|:-:|
|Before|
|![image](https://user-images.githubusercontent.com/31519867/188603787-39c5c5d6-f2bf-40f1-b7be-a9ad5351b06c.png)|
|![image](https://user-images.githubusercontent.com/31519867/188603249-dc053fed-4a8b-4888-9fca-9deaea1a21e4.png)|
|After|
|Light|
|:-:|
|Before|
|![image](https://user-images.githubusercontent.com/31519867/188603685-5a6323e5-7a14-4e7f-a090-7fd66be42158.png)|
|![image](https://user-images.githubusercontent.com/31519867/188603479-1072c872-f0a2-429c-a5e2-e9d0724f1875.png)|
|After|
> fix: custom card icon colors

- .github/pull_request_template.md
Add before/after template for screenshots for a more efficient workflow
- Easier to compare for UI changes
> chore: add before/after screenshot tempate

- src/pages/wallets/[walletid].js
zoom level was going below the minimum zoom and not showing the wallets when in mobile.
Fixes #844
https://user-images.githubusercontent.com/63400531/190059724-04d9b94b-8fcc-4487-9b1d-e9764602befc.mp4
> fix: fixed mobile display issues

- src/pages/tokens/[tokenid].js
Added a Minted On date for the info panel
Fixes #964 
- [ x] New feature (non-breaking change which adds functionality)
Before is no minted on information
After on Mobile:
After on screens bigger than Mobile:
> fix: added Minted on Date

- src/pages/tokens/[tokenid].js
Fixes #977
Add `UUIDTag` to breadcrumb
| ![image](https://user-images.githubusercontent.com/31519867/191468665-4e30f258-2b98-4c8e-b71a-4c2ca0e60e2b.png) | ![image](https://user-images.githubusercontent.com/31519867/191468535-0b1750cb-41ad-49f0-a67c-56eb85545554.png)|
> fix(token): token id too long in breadcrumb

- src/components/PlanterQuote.js
Update layout of `PlanterQuote`
See https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=7739%3A36660
| ![image](https://user-images.githubusercontent.com/31519867/191480036-8c16c63c-c830-4a08-a28f-72e72c34c6b0.png) | ![image](https://user-images.githubusercontent.com/31519867/191480136-7bc9ca24-91be-4aa8-8fd3-1af2b6c664bf.png) |
> fix(planter-quote): layout not conform design

- src/components/Drawer.js
Remove the `onClick`
Add click event listener
Fixes #863
> fix: drawer title not clickable

- src/components/FeaturedTreesSlider/index.js
- src/components/Link.js
Fixes #1010
**Problem**: The cards were not of the same height since the height was not defined for the cards wrapped inside the `<Link/>` component.
**Solution**: Fixed by changing the `display` property of `Link` to `flex` and adding `flex:1` to `Card` component used in FeatureTreesSlider.
_NOTE_: the changes made in `Link.js` won't affect any areas as we are wrapping a single child component inside `<Link/> `component so changing the display property from `block` to `flex` won't make any ui changes.
|       Before        | …
> fix: inconsistent height of cards

- src/components/TreeSpeciesCard.js
Fixes #992 
**Problem**: The layout for card was broken for longer names.
**Solution**: Add wordWrap and fixed width property to limit the name up to particular length and shift the rest to next line.
_NOTE: increased padding for inner card content, the height of the card is slightly increased._
| <img width="359" alt="191858432-41a0f344-c4d4-4c7c-8ba6-3a7e84c47e54" src="https://user-images.githubusercontent.com/68511458/192595816-0e3d708e-5c …
> fix: broken layout for longer names

- src/components/FeaturedTreesSlider/index.js
- src/components/Link.js
reverts Greenstand/treetracker-web-map-client#1015
This commit is causing problems with every link on the web map like: #1032
Should re-open #1010
> revert "fix: inconsistent height of cards"

- src/context/themeContext.js
- src/models/pathResolver.test.js
Update the background color of timeline button in dark theme
Fixes #895 
|  <img width="571" alt="image" src="https://user-images.githubusercontent.com/29462498/191710373-75fd486b-2b2e-41f7-bf7b-6015a82a7b56.png">  |  <img width="563" alt="image" src="https://user-images.githubusercontent.com/29462498/191710758-12dbca67-2cdc-42bb-b520-075e92c3f5b2.png"> |
> fix(ui): theme dark background timeline button

- src/components/TreeInfoDialog.js
Update the display size of tree info dialog
Fixes #991 
The full screen display of tree info dialog happens only in mobile screens
https://user-images.githubusercontent.com/29462498/192101271-4387c702-860a-43bb-9d66-ec266b621f5f.mov
> fix(ui): make the tree info dialog full screen on mobile

- CHANGELOG.md
- src/components/PlanterQuote.js
Fixes #947
Not able to find planter quote in the org page to add screenshots of the changes.
> Feat: location for planter info on org page

- src/pages/admin/theme.js
- fix: parsed theme was not using the spread operator
> fix(playground): textarea not updating theme values

- src/pages/wallets/[walletid].js
Fixes #1092
Passed a link prop to the FeatureTreesSlider component to redirect to the wallet link of that tree.
> Fix: Wallet page wrong link 

- src/pages/trees/[treeid].js
Fixed latitude/longitude icon color from pink to grey to make it consistent with other icons
Fixes #1101 
| <img width="515" alt="Screenshot 2022-10-12 at 12 14 10 PM" src="https://user-images.githubusercontent.com/41188167/195275131-bdabcba5-a4ef-4e23-a4e4-e6f3d3db05ed.png"> | <img width="515" alt="Screenshot 2022-10-12 at 12 14 26 PM" src="https://user-images.githubusercontent.com/41188167/195275227-4b1ac12f-1b34-43be-b0d3-3c8bde2e437f.png"> |
> fix(tree): make global icon consistent with others

- src/pages/wallets/[walletid].js
Reverts Greenstand/treetracker-web-map-client#1111
Have to revert it, the uuid component doesn't work on this case, hovering mouse on it can not show the complete ID
> Revert "feat: shorten token id"

- src/components/ImpactSection.js
- update styling to be `flex: 1`
Fixes #1118
> fix(impact): cards not vertically aligned

- src/hooks/globalHooks/useLocalStorage.js
- change initial state back to default value
Fixes issues with the theme playground and bread crumb colors
> fix(hooks): localstorage initial state is undefined

- src/components/FeaturedPlantersSlider/index.js
- src/components/FeaturedTreesSlider/index.js
Fixes #1057
- Bug fix (non-breaking change which fixes an issue)
| <img width="707" alt="before" src="https://user-images.githubusercontent.com/53157755/197322517-f463db54-0d49-4751-86eb-765601ddac4f.png"> | <img width="725" alt="after" src="https://user-images.githubusercontent.com/53157755/197322521-af1fd15e-3470-4523-9d69-4fcd5e6adf0f.png"> |
- I have performed a self-review of my own code
> fix: Make slider button visible

- src/style.css
Fixes #501 
- Bug fix (non-breaking change which fixes an issue)
| <img width="549" alt="beforeFont" src="https://user-images.githubusercontent.com/53157755/197327746-674c1e0d-9fa9-4905-acf4-e091c753547c.png"> | <img width="572" alt="AfterFont" src="https://user-images.githubusercontent.com/53157755/197327748-ec3a15b9-5bc2-44a9-b2bf-27cc73cb8a30.png"> |
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
> fix: Match figma font

- src/pages/organizations/[organizationid].js
- src/pages/planters/[planterid].js
There was a div tag inside a p tag in multiple locations. That was breaking the layout. Changing the div to a span fixed the layout issue.
Fixes #1118
| <img width="676" alt="before-stacked" src="https://user-images.githubusercontent.com/53157755/197720828-6ac579f8-a36f-4579-b771-97444e415ce9.png"> | <img width="691" alt="after-stacked-fix" src="https://user-images.githubusercontent.com/53157755/197720846-6a9f63af-a988-4953-aeda-c47cf9003800.png"> |
> fix: align cards horizontally

- src/components/Timeline.js
- src/context/themeContext.js
- change `Box` to `Paper` to adjust background color
- remove unused `timeline` colors in `themeContext`
- fix `kebab-case` not supported for sx properties
Fixes #895
|![image](https://user-images.githubusercontent.com/31519867/198826292-173067fd-9486-4206-97a3-b03b042fc2b4.png)|![image](https://user-images.githubusercontent.com/31519867/198826277-ad34ab78-d47c-4549-9c2f-112f0f6950f8.png)|
> fix(timeline): background color is not equal to navbar

- src/components/TagChips.js
- change text color to `primary.contrastText`
> fix: tagchips color not compatible custom theme

- src/pages/404.js
- src/style.css
- change styling to inherit from MUI button
|       Before        |
| :-----------------:|
|After|
|:-:|
> feat(404): update back home button to be compatible with custom theme

- src/components/playground/ColorInput.js
- src/components/playground/TypographyInput.js
[comment]: #
added reset button to the typography section in admin/theme also made the css changes to the color selection area
Fixes #1161 
before, no button 
- [x ] Cypress component tests
> 1161 add reset typography input buttons

- src/components/playground/FontSelector.js
- src/components/playground/TypographyInput.js
> feat(theme): add icon alongside custom font

- src/components/Home.js
Make text readable on hover.
| <img width="200" alt="button_before" src="https://user-images.githubusercontent.com/53157755/202338233-2f19de16-fc06-43aa-b795-036348a69f8e.png"> | <img width="194" alt="button_after" src="https://user-images.githubusercontent.com/53157755/202338225-9a041674-0941-4b13-8f10-7a9403336878.png">|
> fix: Change text color on hover

- package-lock.json
- src/pages/admin/theme.cy.js
Reverts Greenstand/treetracker-web-map-client#1198
I temporarily withdraw this, please raise PR again when we solved:
fix #1225 
https://github.com/Greenstand/treetracker-web-map-client/pull/1222#issuecomment-1334737920
> Revert "fix: added a simple mount test for theme in cypress"

- package-lock.json
- src/components/LayoutEmbed.js
When the expand button is clicked, The timeline filter would disappear. This PR corrects this issue. 
Fixes # 1193
| ![image](https://user-images.githubusercontent.com/5744708/202387842-31707db3-c5d7-4f61-921a-9cc8688c9d8f.png) | ![image](https://user-images.githubusercontent.com/30008919/205402928-a9fa8ace-9000-4ef5-845b-84bf60ffd3d9.png)|
PR Demo (Optional): …
> fix: timeline appears on when expand button is clicked

- src/hooks/globalHooks/useLocalStorage.js
Fixes #1267
Adds a prefix to the keys used to store values in localStorage specific to greenstand project
NOTE: Used ''greenstand-web-map-client-" as prefix since we have other projects where we might need to use localStorage and can have greenstand-projectname as prefix @dadiorchen @RubenSmn 
> feat: add prefix

- src/pages/organizations/[organizationid].js
Replace hardcoded continent value for CustomWorldMap with prop.
> fix: CustomWorldMap on organization page

- src/components/GlobalMapLayout.js
Textfield alignment breaks when invalid value is entered in the zoom field. Fixed it.
| <img width="996" alt="not-a" src="https://user-images.githubusercontent.com/53157755/208324976-c177e1e2-e4a1-4f2f-b250-153058ce974b.png"> | <img width="1065" alt="a" src="https://user-images.githubusercontent.com/53157755/208324978-0f207a3e-c07e-4434-a625-fa7e2bbfc13c.png"> |
> fix: alignment issue with textfield

- src/components/common/TreeTag.js
- src/pages/wallets/[walletid].js
Align TreeTags on the wallet page.
| <img width="658" alt="not aligned" src="https://user-images.githubusercontent.com/53157755/205770368-df6ee916-0d27-4738-bfe2-0bbbc52edf41.png"> | <img width="652" alt="aligned" src="https://user-images.githubusercontent.com/53157755/205769442-892029ab-f7f3-4904-89e1-607d00bdc5b3.png"> |
> fix: alignment issue

- src/components/LayoutEmbed.js
[comment]: # 
background color in the layoutembed.js file was hardcoded a background color of white, this is why it never changed when you changed the theme to dark mode.
Fixes #1236 
- [x ] Bug fix (non-breaking change which fixes an issue)
before: [loomBefore](https://www.loom.com/share/90e72788afec4547b0ebd4e60744a194)
after: [loomAfter](https://www.loom.com/share/eaae4870b05d47fa8c2467dea38e31c0)
myself by looking at the colors 😆 
> fix: embeded background was white in dark mode

- src/components/FeaturedPlantersSlider/style.js
- src/components/FeaturedTreesSlider/style.js
Clicking the button wouldn't scroll to the starting position because the browser would forcefully snap to the snap position.
Fixes #1279 
https://user-images.githubusercontent.com/53157755/206978295-2fb64be0-0983-4483-9be5-f019bf4a7a5e.mp4
> fix: featured Slider bug

- src/components/Home.js
- src/context/themeContext.js
Added in new palette value "#adadad".
[comment]: # 'Updated hard-coded color values in "Let's Find a Tree" and "Learn More" buttons with values found in the Theme Palette. Added a theme palette value named "brightGrey" to have the #adadad value available. resolves #1257'
Fixes #1257
| [before](https://user-images.githubusercontent.com/48111116/208551786-f9eab2c2-79f5-450d-9ae8-2730ed44d373.PNG)
|  [after](https://user-images.githubusercontent.com/48111116/208551846-2d8b3236-d336-4eb6-93a7-b276b661a237.PNG)
Visually looks the same.
> fix(home): replace hard-coded vals with palette vals

- src/pages/trees/[treeid].js
|       Desktop       |       Mobile        |
| <img width="1434" alt="tree_desktop" src="https://user-images.githubusercontent.com/53157755/208785197-37f8fa53-059a-46d0-912a-f1fad0e6eb3c.png"> | <img width="251" alt="tree_mobile" src="https://user-images.githubusercontent.com/53157755/208785207-acaf8170-8172-4490-bdb4-86d58778e0a3.png"> |
> perf: add dimension to tree image

- src/components/common/Info.js
Hard to see icons on dark mode. This fix updates the Icon color for better contrast.
|<img width="490" alt="Organization since July 23, 2020" src="https://user-images.githubusercontent.com/53157755/209021955-b0692b06-8d74-4418-8264-75d208d2d19d.png"> | <img width="372" alt="light-a" src="https://user-images.githubusercontent.com/53157755/209021936-6b50d53d-e66e-4de9-9307-f34102c9e79c.png"> <img width="343" alt="dark-a" src="https://user-images.githubusercontent.com/53157755/209021949-d536e77b-ea8e-45d9-9fda-b10673b4e8ad.png"> |
> fix: icon color 

- src/components/PlanterQuote.js
We don't need separate layouts for reversing the card layout. Avatar can be reversed by using flex: order. This change reduces the file size by 28%.
| <img width="693" alt="before_quote" src="https://user-images.githubusercontent.com/53157755/209026698-f76ec938-5f15-4a55-bdc1-4ff65c5bc624.png"> | <img width="651" alt="after_quote" src="https://user-images.githubusercontent.com/53157755/209026701-31d780c9-780b-4589-9b3e-6349ff5eda3a.png"> <img width="372" alt="after_mobile" src="https://user-images.githubusercontent.com/53157755/209026715-ad59a0dd-3ca3-42bd-8dfb-f6bb6275099e.png"> |
> perf: reduce javascript in planter quote

- src/components/PlanterQuote.js
- src/components/ProfileAvatar.js
Planters' images are shown in the proper orientation on the Organization page.
- Modified the `ProfileAvatar` Component; introduced `sx` props.
- Change the `Avatar` component to the `ProfileAvatar` component and use the `image_rotation` property from the `planter` object.
- Removed unused imports.
Fixes #1306
|:-----------------: | :----------------: |
|![208920633-8c7dd065-5e80-494c-9cbf-21a0c6ccd953](https://user-images.githubusercontent.com/8200073/209155871-dd37fd99-d6d8-48b4-a12e-1b1327081bb0.png) | ![image](https://user-images.githubusercontent.com/8200073/209156843-fd2df136-6b64-4425-891f-73b581fa04ac.png)|
> fix: planter incorrect image rotation on organization page

- README.md
- package.json
- update cypress test command to run nock by default
Fixes @keyy123 struggles with `npm run cy` :wink: 
> chore: cypress command run nock by default

- src/components/playground/TypographyInput.js
Fixes #1353 
Added useEffect statement to reactively update TypographyInput when MUI theme was changed. 
[before](https://user-images.githubusercontent.com/48111116/213859084-516a2d71-c696-486c-b4be-3641e89959eb.PNG)
[after](https://user-images.githubusercontent.com/48111116/213859091-defe7d53-2905-4350-9d80-2a7ae98ad9ce.PNG)
- [ x] Cypress component tests
- [ x] …
> fix(admin/theme): reset typography vals correctly

- scripts/codeshift.js
The script(codemod) written to update the imports to the defined alias was not working for statements containing single constructs ( '../' ). Now it has been generalised to all kinds of import statements.
Fixes #1372
> Feat: update codeshift file to handle all cases

- src/components/Timeline.js
No error is shown when the expand button is clicked and an invalid date range is selected on the timeline. This change fixes it.
> fix: show date error on expand screen

- src/components/FeaturedTreesSlider/test.cy.js
Updated image link in FeaturedTreesSlider so picture shows up.
| <img width="556" alt="before-FeaturedTreesSlider" src="https://user-images.githubusercontent.com/53157755/204113182-8a4b73cc-ba26-4d65-bc8a-a750a2b64e24.png"> | <img width="758" alt="after-FeaturedTreesSlider" src="https://user-images.githubusercontent.com/53157755/204113188-0e98249a-ec2c-4b1b-a051-64a9ec76cadc.png"> |
> fix: FeaturedTreesSlider Test

- src/components/LayoutMobile.js
Change height to window innerheight
Fixes #867
Physical Device | Chrome Simulator
:-:|:-:
> fix: mobile app height incorrect

- src/pages/tokens/[tokenid].js
Transaction history breaks on smaller screen size. This fix aligns the timeline.
| <img width="516" alt="before" src="https://user-images.githubusercontent.com/53157755/207737693-6e7bf590-e731-442a-b33d-ef1dadee7fc5.png"> |<img width="527" alt="after" src="https://user-images.githubusercontent.com/53157755/207737703-ac1e13d6-4a4b-4202-8f87-0d7b779bb854.png"> |
> fix: transaction history on token page

- src/components/Link.js
- migrate makeStyles to `sx` prop
Fixes this warning in the breadcrumbs
```
Warning: Prop `className` did not match. Server: "makeStyles-link-8" Client: "makeStyles-link-1"
```
> fix: react styles warning

- src/pages/trees/[treeid].js
- src/pages/v2/captures/[captureid].js
This is a refactor to rename Tree Info to Capture Info and removes the morphology and gps accuracy tags
Fixes # #1679 
Before:
After:
> refactor: renames tree info to capture info and removes unused tags

- src/components/LayoutEmbed.js
Removes the horizontal scrollbar that appears on an embedded panel
| ![image](https://github.com/Greenstand/treetracker-web-map-client/assets/40811107/46c32c80-3cd2-4476-9977-d6640bd4449c) | ![image](https://github.com/Greenstand/treetracker-web-map-client/assets/40811107/258f98ff-1563-447a-93e0-1a51966f44f1) |
> fix: removes horizontal scrollbar from embedded panel

- src/context/themeContext.js
This change will set the users theme from the OS preferences. If these preferences cannot be accessed then the application will default to the light theme.
The change should not break anything but it's a good idea to test it manually on someone else's machine before merging. To do so you need to delete the previous theme from Application -> Local Storage in dev tools.
> Theme from os

- src/models/utils.js
- src/pages/_error.js
Fixes #1580
Remove redirect for 500 error and use the custom error page to return 500 error. It only works in production due to the design of Next.js, not sure if there is a better way.
| <img width="720" alt="1" src="https://github.com/Greenstand/treetracker-web-map-client/assets/99370786/42433647-6b69-4357-993e-47eee28f0d53"> | <img width="720" alt="2" src="https://github.com/Greenstand/treetracker-web-map-client/assets/99370786/f8f7ce69-89 …
> fix: redirect 500 error

- src/components/App.js
I have fixed the website that allows the page to navigate back to the valid URL instead of the previous bounds
Fixes #725 
[screen-capture.webm](https://github.com/Greenstand/treetracker-web-map-client/assets/81385914/4226689e-2973-4714-9bac-0fa215603409)
> fix: allow page to navigate back to valid url when bounds change

- src/components/ProfileCover.js
|       Desktop        |       Mobile        |
| <img width="1440" alt="cover_desktop" src="https://user-images.githubusercontent.com/53157755/208791528-921ca1d9-fd7f-4186-b350-9186ad4d0b08.png"> | <img width="244" alt="cover_mobile" src="https://user-images.githubusercontent.com/53157755/208791522-58302691-af0e-4e5a-a742-e09d11b904cd.png"> |
> perf: add dimension to cover photo

- src/pages/top.js
[comment]: Fix the  issue #1747: can not jump to bounds on the first view of the top page . Add bounds detection code to top page. Also, I strongly recommend that we should implement the goto function in a shared library rather than in each file just like that:
which may increase the complexity in our project.
Fixes # 1747
| ![Before Image](https://github.com/Greenstand/treetracker-web-map-client/assets/6525061/d161ad0d-2089-449f-95e2-24fa0b436e32) | ![After Image](https://github.com/Greenstand/treetracker-web-map-client/assets/6525061/08436ea6-6efe-467f-ae2f-912f63ccd0c0) …
> fix the issue 1747: can't goto bounds in top page

- src/components/App.js
Change tested by imbedding the web map client into react native webview component.
> feat: add postMessage method to send message to react native webview

- .github/workflows/deploy-main-channel-to-prod.yaml
- .github/workflows/dev-build-release.yaml
> feat: build multiple docker images for multiple envs

- Dockerfile
> fix: run the build inside docker

- .github/workflows/deploy-main-channel-to-dev.yaml
[comment]: Propose fix to issue #1781
Fixes #1781
- [X ] Bug fix (non-breaking change which fixes an issue)
Ran relevant checks
> fixed: added regex validation for version name formatting
