package-lock.json
package.json

This will crash the app when 'npm start'

A tiny problem in the new repo package.json

---

src/map.js

feat: solved the treeid=xxx problem

---

src/map.js

Resolve #20 
Update URL with bounding box so that current location of the map can be shared (in format of /@37.8508569,-122.2524834,17.11z)

To resolve issue 20

---

src/App.js

Fix: 1) timeline icon should not show when side panel is open
timeline icon 
2) should never show when viewing a single tree link (like ?treeid=12312 or ?tree_name=test-name)

fix: 60 issue - show timeline icon when sidepanel is open

---

src/components/Timeline.js

#85 
Elevated timeline container. Positioned right tooltip to bottom.

#85: Tooltip Bugfix

---

src/components/Logo.cy.js
src/components/Logo.js

Resolves #98 
Hi, 
The issue was due to the logo div's height not being static so the click event on zoom couldn't propagate because the div was blocking it.  
By setting the height of the logo div to 50px, it no longer prevents zoom click event from happening
https://user-images.githubusercontent.com/80873472/133403625-b7da83a7-b419-42ae-8149-0fcf741fbd6f.mp4

fix: zoom on mobile issue

---

package-lock.json
package.json
src/App.js
src/components/Timeline.js
src/theme.js

Issue110 - Adjust mui theme for new web map site

---

.github/workflows/treetracker-dev-build-release-deploy.yml

fix: build github actions

---

src/components/Navbar.cy.js
src/components/Navbar.js

Hi, I have made Navbar component. 
I added menu component from material ui as well just so it is mobile responsive but we can probably improve on this in future
.

feat: navbar component

---

src/Home.js
src/components/Layout.js

Layout.js in components folder is a good place to put components and layout that will be the same for most of the application. I have moved the grid layout, navbar and map component to this file because to the best of my knowledge this will be the layout for just about every page in the application. Now when we make a page we will only need to code the left panel. 
If any of the pages don't have this layout we can always make another layout and program the application to use layout based on routes.

refactor: moved common components to layout.js

---

src/components/Home.js
src/components/Layout.js

This part of the home component was mistakenly in layout.js.

chore: moved background image out of layout to home component

---

.env
cypress/integration/integration/top.cy.js
cypress/integration/integration/trees/[treeid].cy.js
next.config.js
src/components/App.js
src/components/Home.js
src/mapContext.js
src/models/Map.js
src/pages/_app.js
src/pages/index.js
src/pages/top.js
src/pages/trees/[treeid].js

implement trees/id page, add integration test.

---

package-lock.json
src/components/App.js
src/components/Home.js
src/components/Layout.js
src/components/Navbar.js
src/components/SidePanel.js
src/models/Map.js
src/models/mapTools.js
src/pages/index.js
src/style.css

I have fixed the issue with the container height for the map for issue resolves #151 
map container width set to 50%

#resolves #151

---

src/pages/trees/[treeid].js

I might be wrong but I think that just by using `mapContext.map` and listening for changes we can do `flyTo` when it is available?
Just trying to try my luck with a PR (: 
Resolves #165

resolves #165

---

src/models/Map.js

Fixes [#93](https://github.com/Greenstand/treetracker-wallet-web/issues/93)

fix: remove zoom control panel #93

---

README.md

docs: added wsl instructions to readme

---

src/common/TreeAge.cy.js
src/common/TreeAge.js

@dadiorchen - please let me know if this needs more work. here is a screenshot from the Cypress test runner, showing the new component:
thanks
resolves #105

feat: style tree age component; resolves #105

---

src/common/Filter.cy.js
src/common/Filter.js

feat: added filter component

---

src/components/BackButton.cy.js
src/components/BackButton.js
src/components/Layout.js
src/components/PageWrapper.js
src/components/SearchButton.cy.js
src/components/SearchButton.js
src/pages/_document.js
src/pages/organizations/[organizationid].js
src/pages/top.js
src/theme.js

I encapsulated reusable portions of the organizationid page into separate component files. 
Created PageWrapper to provide consistent layout between pages.
Improved how page content is filled and sized to prevent overflow caused by page margins/padding. This was mostly achieved by taking advantage of parent containers with `display: flex` and the space filling child element would have `flexGrow: 1`

Page Layout, SearchButton and BackButton component development

---

next.config.js
src/pages/trees/[treeid].js

resolves #217 
depends on #234

[treeid] page development

---

src/pages/trees/[treeid].js

The error that I see is that mock server does not have data to display to the tree information. So, I just added checks to make sure that data exists and then to render image, otherwise image will not render.

fix: #261 error on clicking tree icon

---

src/components/FeaturedTreesSlider/test.cy.js
src/components/Link.js

The purpose of this PR is to fix #250

fix: issue # 250 broken cypress test

---

src/components/common/Filter.cy.js
src/components/common/TreeAge.cy.js

The purpose of this PR is to fix #267

fix: broken cypress test routes

---

package-lock.json
src/style.css

The purpose of this PR is to fix #254

fix: issue #254 recover nearest tree feature

---

package-lock.json
src/components/Home.js
src/components/Layout.js
src/components/Navbar.js

The purpose of this PR is to fix #281
I could not find a menu icon that is the same as the one in the design file. MUI icons don't have one, so I just used a generic menu icon.

style: issue #281 mobile version of home page

---

src/components/Navbar.js

The purpose of this PR is to fix #317

fix: issue #317 navbar disappeared

---

src/components/common/Time.cy.js
src/components/common/Time.js

fix: replace string prop with date and format it

---

.github/pull_request_template.md

feat: create github pull_request_template.md

---

src/components/common/CustomCard.cy.js
src/components/common/CustomCard.js
src/pages/planters/[planterid].js
src/theme.js

Added card component as a common component.
Fixes #307

feat: issue #307 card component

---

cypress/tests/e2e/top.cy.js
src/components/App.js
src/components/Layout.js
src/components/common/Filter.cy.js
src/components/common/Filter.js
src/pages/top.js
src/theme.js

chore: clean useless code, fix the map viewer size problem

---

src/components/VerifiedBadge.js
src/components/common/Location.cy.js
src/components/common/Location.js
src/components/common/Time.cy.js
src/components/common/Time.js
src/pages/planters/[planterid].js

Mount the component with 'theme' in component test files, and fix some design issues as per Figma design file.
Fixes #305 

fix: issue #305 mount the component with theme

---

src/components/App.js
src/components/BackButton.js
src/components/PageWrapper.js

add code logic to the Back button, using useRouter hook.
- [ x] New feature (non-breaking change which adds functionality)
it does not need a test, it's a simple functionality 
#332 
add zoom in and zoom out button for the map.
- [ x] New feature (non-breaking change which adds functionality)

feat: add logic to the Back button #333

---

src/components/App.js

I noticed the App component is broken after recent merges. Here's a quick fix to get the build working again
```
[1] error - ./src/components/App.js:400:6
[1] Syntax error: Expected corresponding JSX closing tag for <Box>.
[1]
[1]   398 |           </div>
[1]   399 |         </div>
[1] > 400 |       </div>
[1]       |       ^
[1]   401 |       <Snackbar
[1]   402 |         open={message.open}
[1]   403 |         autoHideDuration={10000}
```

fix: broken app component / Syntax error stopping production build

---

.github/workflows/pull-request-ci.yml
src/components/BackButton.js

Because of #355 I created a workflow to check linting on all incoming PR. Right now it's just linting but we can add testing as well when it's ready.

CI/CD: Github workflow actions - pull request linting

---

src/components/BackButton.js

Removed makeStyles from backButton component as it was not necessary.
Fixes #359 

fix: issue #359 makeStyles import error

---

package-lock.json
package.json
src/components/App.js

fix: swtich to https to install core

---

package-lock.json

chore: reset lock

---

package-lock.json
package.json

fix: release test

---

Dockerfile

fix: next build

---

src/components/LeaderBoard.cy.js

Add tests for LeaderBoard.js

---

package-lock.json
src/components/common/Filter.js

[comment]: # 'No alert/warning message was being displayed when start date was greater than end date.'
Fixes # error/warning component #341

feat: error/warning component #341

---

.github/workflows/pull-request-ci.yml
cypress/tests/e2e/top.cy.js
cypress/tests/integration/trees/[treeid].cy.js
src/components/LeaderBoard.cy.js
src/components/Navbar.cy.js
src/components/Share.cy.js
src/components/ShareIcon.js
src/components/common/CustomImageWrapper.cy.js
src/components/common/CustomImageWrapper.js
src/components/common/Filter.cy.js
src/models/utils.js
src/models/utils.test.js
src/pages/top.js

Fixes #357 
This pr includes some small fixes to get all of our tests to pass. I also updated the PR workflow to run all of these tests.
One change that should be noted is the `formatDateString()` util function I created. It formats the date based on the client's timezone. This also effects test environments so the testing is a little loose:
```js
expect(['18/10/2020', '19/10/2020']).toContain(formattedDate);
```
I used `en-GB` date formatting to match the design doc. Perhaps there is a way to selectively format the date in American or European formats based on client timezone. I see we have the `moment` package installed which may help with that.

Add testing to PR workflow and fix all failing tests

---

src/pages/organizations/[organizationid].js

Added white background to the logo in the organization page for improved visibility
[comment]: # 280 
Fixes #280 

style: add white background to the logo in organization page

---

src/components/common/Filter.js

Fixed layout issue. Placed the input fields next to each other based on the Figma design.
Fixes #400

style: issue #400 filter layout flaw

---

cypress/tests/integration/organizations/[organizationid].cy.js
src/pages/organizations/[organizationid].js

Fixed typography and layout issues on the organization page. Along with the Divider component.
Fixes #410

style: org page typography layout

---

src/pages/top.js

Fixed typography issue
Fixes #405

style: issue #405 typography issue on top page

---

cypress/tests/e2e/top.cy.js
cypress/tests/integration/organizations/[organizationid].cy.js
next.config.js
src/components/FeaturedTreesSlider/index.js
src/components/common/Filter.cy.js
src/models/utils.js
src/pages/planters/[planterid].js
src/pages/top.js
src/pages/trees/[treeid].js

Use real api service

---

src/components/Home.js

Refine the home page

---

next.config.js
src/components/PageWrapper.js
src/components/TreeSpeciesCard.js
src/components/common/CustomCard.js
src/components/common/DataTag.js
src/pages/planters/[planterid].js
src/theme.js

Refine planter page. 
We lost some information from the API. Planter mission and about text is now missing, added some placeholder text until it is fixed.
Species are missing from the API added placeholder data for now.
planter.time_created is also missing.
Removed featured tree slider and added world map component instead as seen in the Figma design.
On mobile device around the world map, the margins are not exact because of the SVG dimension.
Dividers are not going all the way to the edge of the "page" because of the padding. We would need negative margins here which I personally wouldn't use, feels sketchy. What do you think?
Fixes #443

style: issue #443 refine planter page

---

next.config.js
src/components/PageWrapper.js
src/components/TreeSpeciesCard.js
src/components/common/CustomCard.js
src/components/common/DataTag.js
src/models/utils.js
src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js
src/style.css
src/theme.js

Refined org page. Used placeholders everywhere where API does not return proper data. 
Fixes #444

Stlye/issue #444 refine org page

---

src/components/LeaderBoard.js
src/models/utils.js

Created a function to fix the non-official country names. Placed it in the utils.js file. Other faulty country names should be added later on.
Fixes #449

fix: issue #449 broken flags

---

src/components/Drawer.js
src/components/FeaturedTreesSlider/style.js
src/components/LeaderBoard.js
src/components/PageWrapper.js
src/components/TreeSpeciesCard.js
src/components/VerifiedBadge.js
src/components/common/CustomCard.js
src/components/common/DataTag.js
src/components/common/Filter.js
src/models/utils.js
src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js
src/pages/top.js
src/pages/trees/[treeid].js
src/theme.js

style: issue #441 refine top page

---

package-lock.json
package.json
src/components/App.js

Updated web-map-core to v1.4.2 and changed the iconSuite parameters to match the new icons

Update web-map-core version and change iconSuite parameter

---

src/theme.js

Fixes # 434
- [x ] Any dependent changes have been merged and published in downstream modules

fix(css): Change MUI theme default letter spacing to 0. Fixes issue #434

---

src/components/TagChips.cy.js
src/components/TagChips.js
src/pages/top.js

[comment]: # Added tag chip component for the continents. 
Fixes #427 
Desktop 
Mobile 

feat: add continent tag chip

---

package-lock.json
package.json

feat: upgrade core

---

package-lock.json

automatic fix for this security warning:
follow-redirects  <1.14.8
Severity: moderate
Exposure of Sensitive Information to an Unauthorized Actor in follow-redirects - https://github.com/advisories/GHSA-pw2r-vq6v-hr8c
fix available via `npm audit fix`
node_modules/follow-redirects

fix: follow-redirects security warning

---

.env

The api route needed to be updated.

fix: change api route

---

.github/workflows/treetracker-dev-build-release-deploy.yml
.github/workflows/treetracker-prod-cdn-deploy.yml

Adds e2e testing to deployment workflow

ci: add e2e tests to deployment workflow

---

src/models/Map.js

fix: support token id

---

src/models/Map.js

fix: no logo

---

src/models/Map.js

fix: bad tiles

---

src/components/Layout.js

Fix background for the dark theme.
Fixes #499

style: issue #499 dark theme bg

---

src/pages/planters/[planterid].js

Although this issue got deleted, it got pushed with one of the commits. So now there was a duplicate section on the planter page. Which I deleted.
Fixes #484

fix: issue #484 duplicate section

---

src/components/Navbar.js

fix: issue #497 move theme button

---

src/components/PageWrapper.js
src/components/Share.cy.js
src/components/Share.js
src/components/common/CustomShareIcon.cy.js
src/components/common/CustomShareIcon.js

Adds a share button to organization, planter, and tree pages. Closes #460 

Add share button

---

src/pages/planters/[planterid].js

Fix for previous pull request https://github.com/Greenstand/treetracker-web-map-client/pull/463
Fixes # (463)
Style upgrade

fix: refine planter image #463

---

.releaserc

feat: release enable web map iste

---

src/components/TreeSpeciesCard.js
src/components/common/ColorButton.js
src/components/common/CustomCard.js
src/context/themeContext.js
src/pages/planters/[planterid].js

org page ui

---

package-lock.json
package.json
src/components/ShareDeprecated.cy.js
src/components/ShareDeprecated.js
src/components/common/CustomShareIcon.js
src/images/icons/share.svg
src/pages/trees/[treeid].js

Share button, max button

---

src/components/PageWrapper.js
src/components/Share.js
src/components/ShareDeprecated.cy.js
src/components/SidePanel.js
src/components/common/CustomShareIcon.js

chore: share box layout

---

src/components/Drawer.cy.js
src/components/Drawer.js
src/components/DrawerDeprecated.js
src/components/LayoutMobile.js
src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js
src/pages/top.js
src/pages/trees/[treeid].js

Drawer improvement

---

package-lock.json

Fixes # updated package-lock.json file
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation

fix: updated package.json

---

src/components/LayoutMobile.js

Fixes #598 
no cy test files available
- [x ] Any dependent changes have been merged and published in downstream modules

feat: add new zoom-in-out button on mobile

---

src/components/ChangeThemeButton.cy.js
src/components/ChangeThemeButton.js
src/components/Navbar.js

Added a new component `ChangeThemeButton` which improves the UI/UX by showing an icon instead of the text *THEME*.
It also improves code by removing the changing logic from the `Navbar`.
The button works for desktop and mobile navigation.
Light Mode
Dark Mode

feat: add change theme button

---

src/components/Drawer.js

Fix rounded border radius when drawer is docked.
Closes #596
Docked | Undocked
:-:|:-:

fix(drawer): rounded border radius when docked

---

src/components/FeaturedPlantersSlider/index.js
src/components/Share.cy.js
src/components/ShareDeprecated.cy.js
src/components/common/CustomShareIcon.js

Various unit test errors. The only one that may need some clarification would be CustomShareIcon. I changed this to primary main on the palette as I'm unaware of primaryLight as a theme, so I assume it was a typo? Let me know if I am wrong though, or if this should be a different palette color altogether. 
Fixes #521
- Cypress integration
- Cypress component tests
- I have performed a self-review of my own code
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

fix: cypress unit tests - resolves #521

---

src/components/Drawer.js

Add check to see if component reference exists.
Fixes #581

fix(drawer): unmount runtime error

---

src/components/FeaturedPlantersSlider/index.js
src/components/FeaturedPlantersSlider/style.js

Fixes #613
My changes generate no new warnings

feat: added tooltip to display planters/orgs name

---

src/components/FeaturedPlantersSlider/index.js
src/components/FeaturedTreesSlider/index.js
src/pages/top.js

feat: hid scroll button(left,right) on mobile devices

---

src/components/FeaturedTreesSlider/index.js
src/models/utils.js

feat: used image api for tree thumbnail images

---

src/components/Drawer.js
src/components/LayoutMobile.js

fix: drawer incorrect initial theme mode

---

src/components/TreeSpeciesCard.js
src/pages/planters/[planterid].js

Improves the ui by adding support for large numbers of planted trees. See screenshots for changes.
Fixes #611
Before|After
:-:|:-:

refactor: improve ui layout to support large numbers

---

src/components/CustomWorldMap.js
src/pages/planters/[planterid].js

feat: showed continent name from planter data in planter page

---

src/pages/trees/[treeid].js

feat: showed planter info on top of tree page

---

src/components/TreeSpeciesCard.js

Formats large count such as 1.000.000 to 1M

refactor: format large tree count

---

src/components/LayoutEmbed.js
src/images/min.svg

Change the button icon to minimize version
Fixes #556

refactor: update to min icon on embed layout

---

src/components/TreeInfoDialog.js

fix: zoom buttons overlapping dialog

---

src/components/FeaturedTreesSlider/test.cy.js
src/models/utils.js

fix: replaced unrelevant keys in unit tests

---

cypress/tests/integration/wallets/[walletid].cy.js
doc/examples/wallets/180Earth.json
src/models/api.js
src/models/apiPaths.js
src/pages/wallets/[walletid].js

feat: implemented wallet page

---

README.md

Link was not working due to typo

fix: typo on link

---

src/components/CustomWorldMap.js
src/pages/wallets/[walletid].js

feat: added small map for wallet page

---

src/context/playgroundContext.js

Temp theme was not using the spread operator
Fixes #672

fix(playground): temp theme

---

src/components/App.js

feat: updated url when user moves map

---

src/components/LayoutEmbed.js

Fixed the animation
Refactored some to improve readability
Fixes #594

fix: drawer animation

---

cypress/tests/integration/top.cy.js
src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js
src/pages/top.js
src/pages/trees/[treeid].js
src/pages/wallets/[walletid].js

fix top.cy.js

---

.github/workflows/pull-request-ci.yml
src/pages/top.js

chore: test

---

src/context/themeContext.js
src/pages/admin/theme.js

Preview the theme does not reload whole Web Map anymore
Refactor to prevent duplication

refactor: iframe theme preview

---

src/pages/admin/theme.js

fix(playground): iframe border

---

src/components/playground/ColorInput.js
src/components/playground/ColorThumbnail.js
src/context/playgroundContext.js

Fix prop values incorrect on startup
ColorThumbnail and ColorInput did not have correct values

fix(playground): prop values incorrect on startup

---

src/components/LayoutDashboard.js

temporarily disable keycloak

---

src/context/playgroundContext.js
src/context/themeContext.js

Fixes the runtime error
Fixes  #690

fix(playground): runtime error prop dark

---

src/components/Drawer.js

Fixes #597
Tested the responsiveness by adding multiple extra components that do not exists by default. See the screenshot above.

fix(drawer): not able to scroll to bottom content

---

src/pages/tokens/[tokenid].js

Fixes https://github.com/Greenstand/treetracker-web-map-client/pull/664#discussion_r931862887

fix: removed cache from token page

---

src/context/themeContext.js

Theme mode toggle was not working due to no support for the default theme
Fixes #698

fix: theme mode toggle

---

package-lock.json
src/components/FeaturedPlantersSlider/index.js

Made cursor turn into pointer when user hover over slider element.
Fix #703 

fix: made cursor to pointer on slider hover

---

cypress/tests/integration/top.cy.js
package-lock.json
src/components/FeaturedPlantersSlider/index.js
src/pages/top.js

top featured org/planter

---

src/components/FeaturedPlantersSlider/index.js

Made changed to slider button, increased opacity and centered vertically
Fixes (#735)

fix: increased opacity and centered slider button

---

src/components/common/CustomCard.js
src/pages/trees/[treeid].js

Added a tool tip to the CustomCard component. Used by passing tool tip to props.
Fixes (#751)

feat: added tooltip to CustomCard

---

src/context/themeContext.js

fix(playground): preview button not working

---

src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js
src/pages/tokens/[tokenid].js
src/pages/trees/[treeid].js
src/pages/wallets/[walletid].js

Handle no data planter page
Fixes  #737

feat: handle no data detail pages

---

package.json
src/pages/trees/[treeid].js

Reverts Greenstand/treetracker-web-map-client#765

Revert "feat: single tree selector"

---

src/components/ImpactSection.js

[comment]: # fixed another SvgIcon I missed in a previous PR
Fixes #769 
visual checks
- [ x] I have commented my code, particularly in hard-to-understand areas

fix: fixed the impact graph to the new svg icon

---

.gitignore

Ignores swap files for git
For the vim users : )

chore: ignore swap files

---

src/pages/planters/[planterid].js

[comment]: # 'made images look better on planter pages on various sizing'
Fixes #730 
visual tests

fix: made images look better

---

src/components/ImpactSection.js

Fixes the 'coming soon' text to be centered

fix: miss-aligned text

---

src/components/ImpactSection.js

- Add height for mobile
- Add height on svg, also improves height on desktop
Fixes #783 

fix: impact graph height

---

src/context/themeContext.js

fix: inverted initial theme mode

---

package-lock.json
src/components/Share.js

The following changes have been implemented:
- Run useEffect on state change.
- Remove the showmessage function.
resolves #676

Share by code/facebook/twitter#676

---

src/pages/trees/[treeid].js

back button

---

src/components/TreeSpeciesCard.js
src/pages/organizations/[organizationid].js

Fixes warning of component having no key

fix: species component no key

---

src/context/themeContext.js

Fixes custom fonts not loading on preview

fix(playground): custom fonts not loading on preview

---

src/models/utils.js

Reduce font weights by removing doubles

feat(playground): reduce font weights for loading

---

.github/ISSUE_TEMPLATE/basic-issue.md

Add figma design link on issue template to provide more infomation

docs: add figma design on issue template

---

src/components/TreeInfoDialog.js

fix: dialog not fullscreen, header spacing

---

src/components/ProfileAvatar.js
src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js

Add transparent background as discussed in the issue
Fixes #780 

fix: ui profile avatar

---

src/pages/planters/[planterid].js

Added featured tree slider for planter.
Fixes (#814)

feat: added featured trees for planter

---

src/components/App.js
src/components/TreeSpeciesCard.js
src/pages/organizations/[organizationid].js
src/pages/trees/[treeid].js

feat: add link for species

---

src/components/FeaturedPlantersSlider/index.js
src/pages/top.js

Reverts Greenstand/treetracker-web-map-client#836

Revert "ISR/Cache for /top"

---

src/components/LayoutEmbed.js

fix: second scrollbar embed pages

---

cypress/tests/integration/top.cy.js
src/components/FeaturedPlantersSlider/index.js
src/pages/top.js

[comment]: # 'Added wallets of the week section to TOP page'
Fixes #699 
visual

feat: added featured wallets this week

---

src/components/common/Crumbs.js

- fixed typo in `Crumbs` component function name
- new style of the `Crumbs` component
Fixes #875

feat: new style of the Crumbs component

---

package-lock.json
package.json
src/components/common/UUIDTag.js
src/hooks/globalHooks/index.js
src/hooks/globalHooks/useClipboard.js
src/pages/tokens/[tokenid].js

Add plain box component and sx for styling
Fixes #823

feat: add uuid tag

---

src/components/Timeline.js

Add functionality to filter the map when the time frame changes

feat: add timeline filter functionality

---

src/components/common/TagList.js
src/pages/trees/[treeid].js

Improvement on #837
Add `TagList` which renders the tags based on the disabled value
Refactor
Top -  render with `TagList`
Bottom - old with `if-else`

refactor: render order based on disabled prop

---

src/pages/wallets/[walletid].js

Fixes #817
Only did the wallet page, if this is the way we want to go I will update the other pages!
Some research on `display: none` for SEO
- https://www.quora.com/Will-using-display-none-hurt-SEO
- https://www.burkdigitalfactory.com/blog/seo-css-display-none-is-it-bad-to-hide-content/
- https://webmasters.stackexchange.com/a/1384

refactor: tab visibility to improve seo

---

src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js

refactor: visibility for rest of the tabs to improve seo

---

src/components/common/TagList.js

Add explanation for `TagList`
Based on the feedback in #896

chore: add comments for taglist

---

src/pages/tokens/[tokenid].js

Refactor TreeTags for the tokenpage

refactor: taglist token page

---

src/pages/trees/[treeid].js

Fixes #715 
Mobile View:
Screens bigger than mobile:

Add info tree page 715

---

src/pages/planters/[planterid].js
src/pages/wallets/[walletid].js

fix: corrected the dates to when they were created

---

src/pages/organizations/[organizationid].js

[comment]: # 'Added a featured trees slider on organization page
Fixes #876 
- [ x] New and existing unit tests pass locally with my changes

feat: finished up adding tree slider

---

src/components/common/Crumbs.js

fix: react unique key warning

---

src/components/common/Crumbs.js

fix: centered the image

---

src/pages/trees/[treeid].js

Fix tree located in null
Before|After
:-:|:-:

fix: tree located in null

---

src/pages/organizations/[organizationid].js

fix: added organization logo

---

src/pages/trees/[treeid].js

Bug fix. Added assertion that variable `organization` is not null.
Fixes #958

fix: error case: http://localhost:3000/organizations/1332/trees/2578565

---

src/components/ProfileAvatar.js
src/pages/planters/[planterid].js

fix: planter image rotation

---

src/components/Timeline.js

Fix issue with conditional statement

fix: timeline not correct position

---

src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js
src/pages/tokens/[tokenid].js
src/pages/trees/[treeid].js
src/pages/wallets/[walletid].js

placed document calls in SSR components inside of a function to prevent errors from document not existing on server side from initial render
another possible approach is a custom hook that checks if rendered and calls after, but the approach here provided by @RubenSmn (from #813) seems to work good
Fixes #939 #813 

fix: document in SSR error

---

src/models/utils.js
src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js
src/pages/tokens/[tokenid].js
src/pages/trees/[treeid].js
src/pages/wallets/[walletid].js

fix: 500 page showing in production env

---

src/components/Navbar.js

Fix closing menubar of top navbar on mobile screen
Fixes #795 
Video screenshot before 
https://user-images.githubusercontent.com/29462498/191741130-dbae866e-df9e-47ee-8e31-18e360b047fa.mov
Video screenshot after
https://user-images.githubusercontent.com/29462498/191740885-1c2ca142-d60a-4dc5-bfd5-919c8e78a89b.mov

fix: menubar handle click function on mobile screen

---

src/components/InformationCard1.js
src/pages/trees/[treeid].js

[comment]:
added @RubenSmn changes from https://github.com/Greenstand/treetracker-web-map-client/pull/981
Fixes #989 
- [x ] Bug fix (non-breaking change which fixes an issue)
planter.image_rotation is null so no visual changes

fix(tree): fixed rotation problem

---

src/components/common/CustomCard.js

- refactor: update style logic
- fix: height not same if text too long

refacor: custom-card style

---

src/components/Timeline.js

- Remove duplicate `Box` caused by 1fd64357fa4e0385184beef012b7eed04a8fb48b

fix(timeline): double box component

---

src/components/Share.js
src/components/TreeInfoDialog.js

Add functionality to share button
Fixes #804 

feat: treedialog share button functionality

---

CHANGELOG.md
package.json
src/components/ImpactSection.js
src/components/LeaderBoard.js
src/components/Timeline.js
src/components/TreeInfoDialog.js
src/components/common/CustomCard.js
src/components/common/CustomIcon.js
src/components/common/Info.js
src/components/common/TreeTag.js
src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js
src/pages/tokens/[tokenid].js
src/pages/top.js
src/pages/trees/[treeid].js
src/pages/wallets/[walletid].js

- Add custom Icon component
- Implement custom Icon in `CustomCard`
- Update `CustomCard` sx to iconProps to make the function/purpose more explicit
- Change `SvgIcon` to the custom Icon
Fixes #994 #843  #549

feat: add custom Icon component

---

src/pages/trees/[treeid].js

- add planter logo on embed page
Fixes #1034

fix: no planter logo on embed tree page

---

src/components/TreeInfoDialog.js

fix: made some css adjustments

---

src/components/TreeSpeciesCard.js

Fixes #992 
**Problem**: The layout for card was broken for longer names.
**Solution**: Add wordWrap and fixed width property to limit the name up to particular length and shift the rest to next line.
_NOTE: increased padding for inner card content, the height of the card is slightly increased._
| <img width="359" alt="191858432-41a0f344-c4d4-4c7c-8ba6-3a7e84c47e54" src="https://user-images.githubusercontent.com/68511458/192595816-0e3d708e-5c …

feat: update count element styling

---

cypress/tests/integration/wallets/[walletid].cy.js
src/pages/planters/[planterid].js
src/pages/wallets/[walletid].js

[comment]: # 
Added tree slider and added the integration test
Fixes #980
- [ x] New feature (non-breaking change which adds functionality)
before has no tree slider
after mobile:
after pages bigger than mobile:
- [ x] Cypress integration
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] Any dependent changes have been merged and published in downstream modules

980 add tree slider wallet

---

src/components/FeaturedTreesSlider/index.js

- update spacings to better align with the [figma design](https://www.figma.com/file/XdYFdjlsHvxehlrkPVYq0l/Greenstand-Webmap?node-id=8229%3A33574)
|![image](https://user-images.githubusercontent.com/31519867/193463099-bb1803e9-c98c-4cea-8e82-88c8cd9a7227.png)|![image](https://user-images.githubusercontent.com/31519867/193463083-493a5810-655c-4ab9-8fda-a9adbeb3927c.png)|

fix(featured-card): update spacings conform design

---

src/pages/trees/[treeid].js

Fixes #953 
Added click to learn more subtitle to species tag if species_desc exist.
|<img width="599" alt="190096206-55a42940-4674-4f02-b035-2d4f0e2f01ca" src="https://user-images.githubusercontent.com/68511458/193928371-626b5673-9047-44e3-834d-e0c992ae3f35.png">|![SCR-20221005-3kl](https://user-images.githubusercontent.com/68511458/193928469-521b305f-e2f8-4511-948d-a9fe7c56f5c0.png)|

Feat: species tag, click to learn more

---

src/models/utils.js
src/models/utils.test.js

- add formatter util for location string

feat(utils): add location string formatter

---

src/pages/organizations/[organizationid].js

Shows real location for org pages.
Fixes #946
|<img width="862" alt="190050779-4881b86c-735e-416d-b2e6-23313203a705" src="https://user-images.githubusercontent.com/68511458/193937535-49ca3dee-838d-469a-b5c0-450029c481a0.png">|![SCR-20221005-4od](https://user-images.githubusercontent.com/68511458/193937581-560ab19f-d62c-4f1e-931c-818917f4b7f6.png)|

feat: add real location for org pages

---

src/pages/planters/[planterid].js

Fixes #1060 
|![SCR-20221005-6ns](https://user-images.githubusercontent.com/68511458/193948205-b7830e42-6e1f-4cf8-adda-bbe95e52062a.png)|![SCR-20221005-6pu](https://user-images.githubusercontent.com/68511458/193948273-da732635-22fd-433e-8266-bb57267c8712.png)|

feat: add real location for planter pages

---

src/pages/trees/[treeid].js

- refactor: context check to a variable
- add: show avatar image based on context
Fixes #1064 

fix: embed logo incorrect url

---

src/pages/wallets/[walletid].js

Sliced the token id and added flex property.
Fixes #1110 
|<img width="688" alt="195311548-1703dfc5-b85c-479e-b18f-cdca7facddf2" src="https://user-images.githubusercontent.com/68511458/195449091-dfca7f47-36f9-4476-b6f0-9967e50a9ca2.png">|![SCR-20221013-3rb](https://user-images.githubusercontent.com/68511458/195454077-32e47e3d-bc93-4580-b6b3-739d1c0fbeb7.png)|

feat: shorten token id

---

src/pages/tokens/[tokenid].js

Fixes #1102 
|![SCR-20221013-6bo](https://user-images.githubusercontent.com/68511458/195463651-4bebb2ef-ad4a-471c-96bd-5e339496e312.jpeg)|![SCR-20221013-685](https://user-images.githubusercontent.com/68511458/195463663-11535990-4b32-4b2f-a259-41ad465b4ef5.jpeg)|

Feat: add wallet logo

---

src/components/playground/ToggleThemeMode.js

Fixes #1083 
| ![194856916-1a3c6b00-a6ba-4880-8acb-c226d5077510](https://user-images.githubusercontent.com/68511458/194930927-3fdd73b2-f157-4bf8-b256-ab872dc3d296.png)|https://user-images.githubusercontent.com/68511458/194931038-92f1dc02-ea48-4c45-afae-dd8404d28fac.mov|

feat: make toggletheme component sticky

---

src/models/themePlaygroundOptions.js

Fixes #1081 
|![SCR-20221011-16m](https://user-images.githubusercontent.com/68511458/194938110-55dc3b7f-6e69-4973-b4be-9d4951e8792d.png)|![SCR-20221011-15n](https://user-images.githubusercontent.com/68511458/194938015-c62ca651-68ff-4d90-bffa-401e2f34a828.png)|

feat: add 0 as valid input for letter spacing

---

src/pages/top.js

feat: render feature section only if data exists

---

src/pages/admin/global.js

feat(dashboard): add navbar tab

---

src/components/playground/JSONTextarea.js
src/components/playground/index.js
src/pages/admin/theme.js

- extract textarea to component
- update styling to be in sync with other inputs
- add tooltip for extra info
Fixes #669

feat(playground): update textarea styling

---

src/hooks/globalHooks/useLocalStorage.js

The bug was due to mismatch between content rendered on server and client. I fixed the bug by accessing local storage on client side.
Fixes #1091 
- Bug fix (non-breaking change which fixes an issue)
https://user-images.githubusercontent.com/53157755/197304215-bbccc527-ad3c-491d-9ee9-9a1848022ae5.mp4
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas

Fix: dark theme bug

---

src/pages/organizations/[organizationid].js

Fixes #1126
|![SCR-20221021-i5c](https://user-images.githubusercontent.com/68511458/197139409-aba056c1-cb6b-4e61-a6eb-ef7b28f58993.jpeg)|![SCR-20221021-i31](https://user-images.githubusercontent.com/68511458/197139615-d0e26bd8-02b4-448c-84ce-606b9b32e468.png)|

Feat: update card text on organisation page

---

src/components/playground/ColorInput.js

Fixes #701 
[video](https://www.loom.com/share/bd55eec296a54a42a2b7365b07179099)
- [x ] Cypress component tests
- [ x] I have commented my code, particularly in hard-to-understand areas

feat: added ability to reset single colors

---

src/components/dashboard/CustomLogo.cy.js
src/components/dashboard/CustomLogo.js

Fixes #1128 
- New feature (non-breaking change which adds functionality)

feat: add custom logo selector

---

src/components/PlanterQuote.js

Fixes #1087 
|![SCR-20221010-whz](https://user-images.githubusercontent.com/68511458/194927242-f4c7c7d5-299f-49dc-b887-a611e3af29ca.jpeg)|![SCR-20221010-wqz](https://user-images.githubusercontent.com/68511458/194927601-c38a3ccc-d3f0-4778-97dd-e4e496d6cf62.png)|

fix: planter quote location issue

---

src/components/LeaderBoard.js

feat: update text on country leader board

---

src/context/playgroundContext.js
src/models/utils.js

-  extract get/set PropByPath function to models to be reuseable

refactor: extract get- set-PropByPath to be reuseable

---

src/components/Layout.js
src/hooks/globalHooks/useLocalStorage.js
src/pages/_app.js

Fixes the theme mode issue where the `children` of the app don't load in the correct mode from localStorage if the mode is `dark`.
Truly fixes #1091 at the source

fix: theme mode issue

---

src/pages/admin/theme.js

- update iframe src hardcoded url with dynamic url

fix(playground): iframe not working on live dev/prod env

---

src/components/playground/FontsList.js
src/components/playground/TypographyInput.cy.js
src/components/playground/TypographyInput.js
src/models/themePlaygroundOptions.js
src/pages/_document.js

Fixes #1082
| ![image](https://user-images.githubusercontent.com/42190301/199075183-a72a7907-a139-4609-909c-00a3bb8a3d29.png) | ![image](https://user-images.githubusercontent.com/42190301/199075322-e6d0485f-aadc-473f-b715-8923531f76bc.png) |

Change FontFamily input to dropdown

---

src/pages/_app.js

feat: Google Analytics

---

src/components/dashboard/CustomizeNavbar.cy.js
src/components/dashboard/CustomizeNavbar.js

feat: Component to modify navbar

---

src/components/GlobalMapLayout.js
src/pages/admin/global.js

feat: admin can now set initial map view

---

package-lock.json
src/pages/admin/theme.cy.js

Created a cypress unit test that confirms if the component (ThemePlayground) from ./src/pages/admin/theme.js is rendered successfully. 
Fixes #1139
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] Cypress component tests

fix: added a simple mount test for theme in cypress

---

src/components/LeaderBoard.js

fix: Overlap on leaderboard

---

package-lock.json
package.json
src/components/dashboard/ChangeLogoSection.js
src/components/dashboard/ChangeNavSection.js
src/components/dashboard/CustomizeNavbar.cy.js
src/components/dashboard/CustomizeNavbar.js
src/context/configContext.js
src/models/config.reducer.js
src/pages/admin/global.js

- update styling of navbar section
- integrate global config state with navbar customization components
- can add a new item
- can update an item
- can reorder items
- can delete an item
[Kooha-2022-11-20-17:58:01.webm](https://user-images.githubusercontent.com/31519867/202915162-fc5e82b1-e05b-4c2a-83b4-762d0ef101a9.webm)

feat: navbar customization

---

src/components/InformationCard1.js

| <img width="686" alt="no-shadow" src="https://user-images.githubusercontent.com/53157755/203228247-3a71ad98-67ca-4e76-9408-8240938f6674.png"> | <img width="679" alt="with-shadow" src="https://user-images.githubusercontent.com/53157755/203228259-ff363e94-f77b-4857-b057-1f2b2fd64838.png"> |

feat: Add filter to card

---

src/pages/tokens/[tokenid].js

fix: Show truncated token id

---

src/components/Share.js

fix: copy correct link from clipboard

---

src/components/InformationCard1.js

Remove border from avatar to match the Figma design.
| <img width="678" alt="with-border" src="https://user-images.githubusercontent.com/53157755/203665968-e6b86975-b5ab-4f69-a618-5ee61ada72ac.png"> | <img width="679" alt="without-border" src="https://user-images.githubusercontent.com/53157755/203665985-a8e68368-f183-47db-9090-53585813e9d4.png"> |

fix: Remove border from avatar

---

src/components/Timeline.js

feat: give error feedback on incorrect date

---

src/components/FeaturedPlantersSlider/index.js

fix: Display name

---

src/pages/_app.js

Capture performance metrics and send them to google analytics.

feat: Send data to google analytics

---

.github/ISSUE_TEMPLATE/component-building.md

Fix typo in component building issue template.

fix: typo in issue template

---

src/components/search/Search.js
src/components/search/SearchDialog.js
src/components/search/SearchHistoryDialog.js
src/components/search/SearchInput.js

feat: Implement search history

---

src/components/Home.js

| <img width="231" alt="before-hover" src="https://user-images.githubusercontent.com/53157755/204112866-389badde-b53d-4308-aa36-542d15747988.png"> | <img width="219" alt="after-hover" src="https://user-images.githubusercontent.com/53157755/204112871-1cd8ea6a-e1b4-4817-a13e-45a812b9549a.png"> |

fix: hover on button

---

src/components/HeadTag.js
src/pages/admin/index.js
src/pages/admin/theme.js
src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js
src/pages/tokens/[tokenid].js
src/pages/top.js
src/pages/trees/[treeid].js
src/pages/wallets/[walletid].js

feat: Add page titles

---

src/pages/404.js
src/pages/500.js

feat: add page title to error pages

---

src/components/common/ColorButton.js
src/components/common/Crumbs.cy.js
src/components/common/CustomShareIcon.js
src/components/common/UUIDTag.js

chore: remove unused imports from common 

---

src/components/ProfileAvatar.js
src/context/themeContext.js

Fixes #954 
| <img width="256" alt="before-avatar" src="https://user-images.githubusercontent.com/53157755/205218225-49fa8bce-f9d2-414a-ada2-d11d6f5fe306.png"> | <img width="395" alt="Light mode" src="https://user-images.githubusercontent.com/53157755/205218191-96f1f1f0-2cb8-4d62-b399-833fcb1b858c.png"> <img width="330" alt="Dark mode" src="https://user-images.githubusercontent.com/53157755/205218197-79009121-d35f-4d88-ae5e-206343c95da1.png"> |

fix: make logo recognizable

---

src/pages/planters/[planterid].js

Ass. is an unclear abbreviation. Better to include all the letters.

chore: update organization card text

---

src/components/PlanterQuote.js

The Prettier check test should pass in the CI.

chore: apply prettier to PlanterQuote

---

src/components/App.js
src/components/Drawer.cy.js
src/components/InformationCard1.js
src/components/playground/SquareIconButton.cy.js
src/models/pathResolver.js
src/models/tools.test.js
src/pages/admin/index.js
src/pages/index.js
src/pages/tokens/[tokenid].js
src/pages/trees/[treeid].js

Replace console logs with loglevel.

chore: replace console logs

---

src/components/search/test.cy.js

feat: add cypress tests for search

---

src/components/common/CustomCard.js

chore: format number 

---

package-lock.json
package.json

feat: core 2.6.0

---

src/components/LeaderBoard.js
src/components/TreeSpeciesCard.js
src/components/common/CustomCard.js
src/models/utils.js
src/pages/organizations/[organizationid].js

Moved number formatting logic used throughout the codebase to a function abbreviateNumber.

refactor: extract number formatting logic

---

src/components/dashboard/ChangeLogoSection.js

feat: add alt attribute 

---

src/components/PlanterQuote.js

Fixes #1282 
|<img width="456" alt="before" src="https://user-images.githubusercontent.com/53157755/207190289-378a41f2-6799-4d9b-ab15-5bba7d454460.png"> | <img width="459" alt="after" src="https://user-images.githubusercontent.com/53157755/207190312-8a44091f-7067-452a-b7f0-22505b176fbc.png">|

fix: update css for planter quote to work with embed

---

src/pages/index.js

index and follow are assumed by default. Specifying the value doesn't make a difference.

refactor: remove unnecessary values

---

src/components/HeadTag.js

feat: add social tags 

---

src/components/FeaturedPlantersSlider/index.js

fix: kebab case warning

---

src/components/HeadTag.js

Add robots meta tag to HeadTag.

feat: add additional meta tag

---

src/components/HeadTag.js

Add twitter meta tags to HeadTag.

feat: add support for twitter

---

src/pages/admin/global.js

feat: add page title to global

---

src/components/Navbar.js
src/context/configContext.js

- feat: implement navbar config
Currently depending on localStorage for the configuation. In the future we'll get this configuration from the server and pass it as a prop.
Fixes #1125

feat: implement navbar config

---

src/pages/organizations/[organizationid].js

chore: remove unused code

---

.github/ISSUE_TEMPLATE/basic-issue.md

- add default "description" title
- add default "to reproduce" section

chore: update issue template

---

.github/workflows/pull-request-ci.yml

- add `paths-ignore` to not run on `.github` or `README.md` file changes

chore: update workflow run paths

---

src/components/CustomWorldMap.js
src/pages/organizations/[organizationid].js
src/pages/wallets/[walletid].js

Abbreviate numbers for CustomWorldMap on wallet page.

fix: format numbers on wallet page

---

src/models/pathResolver.js
src/pages/tokens/[tokenid].js

fix not jump to token

---

src/pages/planters/[planterid].js

[comment]: # 
changed [planterid].js to properly rotate the embed avatar image
Fixes #1311 
**Before**
**After**
Me looking at it
- [ x] New and existing unit tests pass locally with my changes

fix: corrected image rotation

---

src/pages/organizations/[organizationid].js

Remove extra "organization" word in breadcrumbs #1334
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
|       After       |       Before        |
| "screenshot After" |   "Screenshot Before" ![Screenshot at 2022-12-28 18-22-50](https://user-images.githubusercontent.com/55488549/209815373-01c8dd84-68ad-4a4b-8083-f3d5fe677fb6.png)|
- [ x] Cypress integration
- [ x] Cypress component tests
- [x ] Jest unit tests
- [true] I have performed a self-review of my own code
- [ true ] I have made corresponding changes to the documentation
- …

Remove extra organization word in breadcrumbs #1334

---

src/components/playground/ColorInput.js
src/components/playground/ColorThumbnail.js
src/components/playground/SelectColorProp.js
src/components/playground/SelectTypographyProp.js
src/components/playground/TypographyInput.js
src/components/playground/TypographyThumbnail.js
src/context/playgroundContext.js
src/hooks/contextHooks/usePlaygroundTheme.js
src/hooks/contextHooks/usePlaygroundUtils.js
src/hooks/cwmHooks/index.js
src/hooks/cwmHooks/useDefaultValue.js
src/pages/admin/theme.js

- refactor: reduce rerenders on `ColorInput`
- refactor: reduce rerenders on `ColorThumbnail`
- fix: double if statement case
- refactor: create new context for setters
- refactor: reduce rerenders on `TypographyInput`
- refactor: reduce rerenders on `TypographyThumbnail`
- refactor: extract custom hook to deal with default values for reset logic

Refactor: cwm theme editor

---

src/models/api.js
src/models/apiPaths.js
src/models/pathResolver.js
src/pages/v2/captures/[captureid].js

[comment]: # Added V2 captures page
Fixes #1074 
- [ x] New feature (non-breaking change which adds functionality)
Before there was nothing.
After: 

1074 v2 capture page

---

.github/workflows/deploy-beta-channel-to-dev.yaml
.github/workflows/deploy-beta-channel-to-prod.yaml
.github/workflows/deploy-beta-channel-to-test.yaml
.github/workflows/deploy-dev-env.yaml
.github/workflows/treetracker-staging-cdn-deploy.yml

Upgrade node to version 18 in all .yaml files in attempt to fix semantic release error about using node >= 18
Fixes #1364

fix: upgrade node v14 to v18

---

src/pages/500.js

Link color will now change with theme mode.

fix: change link color with mode

---

src/components/TreeLoader.js
src/hooks/usePageLoading.js
src/pages/trees/[treeid].js

Created new component that uses MUIv5 Skeletons to display during [tree.id] transitions.
Also added custom react hook to detect when page is loading.
Fixes #1039
**Before** 
**After**

feat(treeid): added MUIv5 skeleton loader component for tree info panel

---

.github/workflows/dev-build-release.yaml

release test

---

src/pages/tokens/[tokenid].js
src/pages/trees/[treeid].js

The impact section component has been removed from the page token and tree.
Fixes (#1402)
**Before**
**after**

remove impact section

---

src/components/Navbar.js

fix: config hook undefined

---

cypress/tests/integration/moneytree.cy.js
cypress/tests/integration/readme.md
next.config.js
package-lock.json
src/components/Navbar.js

[comment]:
This PR attempts to fix issue #685. It provides a basic documentation for creating cypress integration tests for newcomers. I will supplement with an online loom video instead of windows screenshots which caused issues in a prior PR also attempting to resolve issue #685. 
Fixes # 685

Cypress Integration Documentaton 

---

src/pages/organizations/[organizationid].js

This PR add the article tag to wrapp the about the organization section increasing the SEO
Fixes #1502 

fix: add the article tag to wrapp the about the orgnization section

---

src/pages/organizations/[organizationid].js

Fixes articles wrapping heading and content separately.

fix: article not wrapping whole content

---

package-lock.json
src/pages/organizations/[organizationid].js
src/pages/planters/[planterid].js
src/pages/v2/captures/[captureid].js
src/pages/wallets/[walletid].js

impact section removed

---

src/components/ProfileAvatar.js

Add imagePlaceholder to Avatar component in case src is empty.
Fixes #1509

fix: photo of planter is missing #1509

---

public/robots.txt

Restrict all robots access to the /admin pages.
Fixes: #1505

feat:disallow robots access to admin pages

---

src/pages/planters/[planterid].js

Added time element on planter page

feat: add time element in mobile and pc view on planters page

---

src/pages/organizations/[organizationid].js

Added time element in organization page 
Fixes #1517

feat: added time element in organization page for mobile view

---

src/components/Navbar.js

- update style for navbar items
|![navbar-before-desktop](https://user-images.githubusercontent.com/31519867/233596956-990bb175-63f0-4ddb-b2b1-bd13a1f08cb5.png)|![localhost_3000__bounds=0 000001341104507446289,0,0 000001341104507446289,0](https://user-images.githubusercontent.com/31519867/233596972-cb5a36cd-262e-4727-9825-4586b5097fc2.png)|
|![navbar-before-mobile](https://user-images.githubusercontent.com/31519867/233596963-1fbb66a7-c4f5-412d-a066-4c615ded4d91.png)|![navbar-after-mobile](https://user-images.githubusercontent.com/31519867/233596966-295aa6a7-926e-40a2-bdb6-4dba4ab672a8.png)|

fix: navbar items not vertical centered

---

src/pages/wallets/[walletid].js

ul and li tags are added to the list to improve SEO.
Fixes #1497

feat: ul and li tags added to wallet page

---

src/pages/tokens/[tokenid].js

[comment]:  Added time HTML tag
Fixes #1499

Added time elements

---

src/pages/wallets/[walletid].js

Removes default list style which was introduced by changing the HTML structure.

fix(wallet): default list style showing

---

next.config.js

feat: add redirect for old wallet url

---

src/components/App.js

chore: disable map bounds

---

package-lock.json
package.json

feat: add new map core

---

src/models/api.js
src/models/apiPaths.js
src/pages/top.js

The Migrations were made for only the trees and the planters. 
- planters => growers 
- trees =>  captures
Fixes #1073

Migrate  trees and planters from v1 to  v2 api

---

src/components/common/Crumbs.js

Updated the Crumb component to not wrap the last element under Link component since it refers to the same page and unnecessarily would cause extra API call on click if wrapped under Link component
Fixes #1610

fix: bread-crumb link redirection 

---

.github/dependabot.yml

Commented out code under dependabot.yml to stop auto upgrading of libs
Fixes #1607

fix: disable auto upgrade of libs

---

src/components/LayoutMobile.js

The app crash on a tree icon clicking (mobile version) #1617 
Fixes # 1617
| ["screenshot before" ](https://dadior.s3.ap-northeast-1.amazonaws.com |   |
- [xI have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works

fix: the app crash on a tree icon clicking (mobile version)

---

src/components/FeaturedTreesSlider/index.js
src/pages/v2/captures/[captureid].js

Wrapped tree id with UUID on capture page
Fixes #1581

Feat: wrap tree id with UUID on capture page

---

src/pages/trees/[treeid].js
src/pages/v2/captures/[captureid].js

- Changed the tree info and image description from Planted on to Captured on
Fixes #1634 

fix: Changed the tree info and image description from "Planted" to "Captured"

---

src/pages/trees/[treeid].js
src/pages/v2/captures/[captureid].js

Fix the check to show text on the badge component

fix: badge check on tree and capture pages

---

src/pages/wallets/[walletid].js

Fixes #1684 
uses encodeUri() to wrap params to avoid unescaped characters

fix: unescaped characters in params

---

src/components/ProfileCover.js

perf: add height to cover photo

---

src/pages/v2/captures/[captureid].js

set the default value for organization.stakeholders

chore: Improve error handling by setting a default value for organization.stakeholders[0]

---

src/components/App.js

Parent emit

---

.github/workflows/dev-build-release.yaml
package.json

fix: bump version [skip ci]

---

package.json

chore: trigger ci

---

src/pages/tokens/[tokenid].js

Fixes #1796 
| <img width="364" alt="Screenshot 2024-09-18 at 9 44 08 PM" src="https://github.com/user-attachments/assets/80958bdd-9eeb-45eb-8986-8c72a2d8a8aa"> | <img width="348" alt="Screenshot 2024-09-18 at 9 40 23 PM" src="https://github.com/user-attachments/assets/23ffadab-fa47-4cb8-87d7-fb9d6c9d78d7"> |

fix: sort token transaction history in time order on client side
